<div id="content-wrapper">
	<div id="content-top-left">
		<!-- space for front-page image scroll -->
	</div>
	<div id="content-top-right">
		<h2>Welcome!</h2>
		<p>We're a web and software development firm based in Europe. We develop business orientated solutions such as project
		management and data visualisation software.</p>
		
		<p>We offer custom and pre-made products, and contribute to multiple open source projects and can help your business integrate
		these into businesses of any size.</p>
		
		<p>We Develop Great Software.</p>
	</div>
	<div id="content-left">
		<div class="module-header">
			SERVICES
		</div>
		<div id="service-list_1" class="service-list">
			<!-- list of links pointing to /info/s/{foo} -->
			<div id="service-webdev" class="service-list-item">
				<span class="service-icon"><img src="/assets/images/services/edit_page.png" alt="" width="16px" /></span> 
				<a href="/services/web-dev/"> Web Development</a>
			</div>
			<div id="service-conversion" class="service-list-item">
				<span class="service-icon"><img src="/assets/images/services/edit.png" alt="" width="16px" /></span> 
				<a href="/services/xhtml/"> XHTML Creation</a>
			</div>
			<div id="service-dotnet" class="service-list-item">
				<span class="service-icon"><img src="/assets/images/services/puzzle.png" alt="" width="16px" /></span>
				<a href="/services/dotnet/"> .NET</a>
			</div>
			<div id="service-crossplatform" class="service-list-item">
				<span class="service-icon"><img src="/assets/images/services/refresh.png" alt="" width="16px" /></span> 
				<a href="/services/xplatform/"> Cross Platform </a>
			</div>
			<div id="service-mobile" class="service-list-item list-item-last">
				<span class="service-icon"><img src="/assets/images/services/iphone.png" alt="" width="16px" /></span> 
				<a href="/services/mobile/"> Mobile</a>
			</div>
		</div>
		<div id="services-list_2" class="service-list">
			<div id="service-modules" class="service-list-item">
				<span class="service-icon"><img src="/assets/images/services/add_page.png" alt="" width="16px" /></span>
				<a href="/services/mobile/"> Custom Modules</a>
			</div>
			<div id="service-datavis" class="service-list-item">
				<span class="service-icon"><img src="/assets/images/services/chart.png" alt="" width="16px" /></span>
				<a href="/services/mobile/"> Data Visualization</a>
			</div>
			<div id="service-linuxadmin" class="service-list-item">
				<span class="service-icon"><img src="/assets/images/services/light_bulb.png" alt="" width="16px" /></span>
				<a href="/services/mobile/"> Open Source</a>
			</div>
			<div id="service-codeport" class="service-list-item">
				<span class="service-icon"><img src="/assets/images/services/next.png" alt="" width="16px" /></span>
				<a href="/services/mobile/"> Code Ports</a>
			</div>
		</div>
	</div>
	<div id="content-right">
		<div class="module-header products-module">
			PRODUCTS
		</div>
		<div id="product-projector" class="product-row">
			<div id="projector-icon" class="product-icon" style="background-image:url('/assets/images/chart.png');">
			</div>
			<div id="projector-details" class="product-details">
				<a href="#">Projector</a>
				Complete project management solution.
			</div>
		</div>
		<div id="product-inventory" class="product-row">
			<div id="inventory-icon" class="product-icon" style="background-image:url('/assets/images/shopping_cart.png');">
			</div>
			<div id="inventory-details" class="product-details">
				<a href="#">Product Manager</a>
				Sale to shipping product management.
			</div>
		</div>
	</div>
</div>