<!-- This line outputs the doctype we set in the bootstrap -->
<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
  <title>Zend Framework Global Layout</title>
  <?= $this->headLink()->appendStylesheet('/css/global.css') ?>

  <script type="text/javascript" src="lib/extjs/adapters/ext/ext-base.js"></script>
  <script type="text/javascript" src="lib/extjs/ext-all.js"></script>
</head> 
<body>

<!-- 
    Layouts are a great place to put header and footer content that will be
    needed on all pages that share the same layout.  To understand fully what
    having layouts inside a MVC application mean, check out the Zend_Layout
    section of the manual.
    http://framework.zend.com/manual/en/zend.layout.html
    -->
<div id="header">
    <div id="header-logo" style="float: left">
		WEBKULTURE.NET
    </div>
    <div id="header-navigation" style="float: right">
		<div id="home-link" class="navigation-link">
			<a href="<?= $this->url(array('controller'=>'index'), 'default', true) ?>">
				Home
			</a>
		</div>
		<div id="blog-link" class="navigation-link">
			<a href="<?= $this->url(array('controller'=>'blog'), 'default', true) ?>">
				Blog
			</a>
		</div>
		<div id="contact-link" class="navigation-link">
        	<a href="<?= $this->url(array('action'=>'contact'), 'default', true) ?>">
				Contact
			</a>
		</div>
		<div id="about-link" class="navigation-link">
			<a href="<?= $this->url(array('action'=>'about'), 'default', true) ?>">
				About
			</a>
		</div>
    </div>
</div>

<div id="seperator"></div>

<!-- This next call will now include any content that was generated in the
     dispatching of a controllers action (or series of actions).  -->

<?= $this->layout()->content ?>

<div id="footer"></div>

</body>
</html>