<div id="content-wrapper">
	<div id="services-content-header" class="content-header"></div>
	
	<div id="services-content" class="content-main">
		<div id="services-sidebar" class="content-sidebar">
			<h4>Services</h4>
			<div id="service-list_1" class="service-list">
				<!-- list of links pointing to /info/s/{foo} -->
				<div id="service-webdev" class="service-list-item">
					<span class="service-icon"><img src="/assets/images/services/edit_page.png" alt="" width="16px" /></span> 
					<a href="/services/web-dev/"> Web Development</a>
				</div>
				<div id="service-conversion" class="service-list-item">
					<span class="service-icon"><img src="/assets/images/services/edit.png" alt="" width="16px" /></span> 
					<a href="/services/xhtml/"> XHTML Creation</a>
				</div>
				<div id="service-dotnet" class="service-list-item">
					<span class="service-icon"><img src="/assets/images/services/puzzle.png" alt="" width="16px" /></span>
					<a href="/services/dotnet/"> .NET</a>
				</div>
				<div id="service-crossplatform" class="service-list-item">
					<span class="service-icon"><img src="/assets/images/services/refresh.png" alt="" width="16px" /></span> 
					<a href="/services/xplatform/"> Cross Platform </a>
				</div>
				<div id="service-mobile" class="service-list-item">
					<span class="service-icon"><img src="/assets/images/services/iphone.png" alt="" width="16px" /></span> 
					<a href="/services/mobile/"> Mobile</a>
				</div>
				<div id="service-modules" class="service-list-item">
					<span class="service-icon"><img src="/assets/images/services/add_page.png" alt="" width="16px" /></span>
					<a href="/services/mobile/"> Custom Modules</a>
				</div>
				<div id="service-datavis" class="service-list-item">
					<span class="service-icon"><img src="/assets/images/services/chart.png" alt="" width="16px" /></span>
					<a href="/services/mobile/"> Data Visualization</a>
				</div>
				<div id="service-linuxadmin" class="service-list-item">
					<span class="service-icon"><img src="/assets/images/services/light_bulb.png" alt="" width="16px" /></span>
					<a href="/services/mobile/"> Open Source</a>
				</div>
				<div id="service-codeport" class="service-list-item list-item-last">
					<span class="service-icon"><img src="/assets/images/services/next.png" alt="" width="16px" /></span>
					<a href="/services/mobile/"> Code Ports</a>
				</div>
			</div>
		</div>
		<p>Services delivered by webkulture and descriptions of said services.</p>
	</div>
	<div id="services-content-footer" class="content-footer"></div>
</div>